version: 2
models :
  - name: violencia_escola
    description: Tabela com indicadores que auxiliam entender o cenário de violência
      nas escolas
    columns:
      - name: ano
        description: Ano
      - name: item
        description: Item referente ao tema da pesquisa
      - name: quantidade_escola
        description: Quantidade de escolas que aderiram a resposta
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: tema
        description: Tema da pesquisa
