version: 2

models:
  - name: metricas_tweets
    description: "dbt model for metricas_tweets"
    columns:
      - name: upload_day
        description: "day of scrapping [partition variable]"
      - name: id
        description: "tweet id [primary key]"
      - name: text
        description: "tweet's text content"
      - name: retweet_count
        description: "tweet's quote count"
      - name: created_at
        description: "tweet's retweet count"
      - name: reply_count
        description: "tweet's reply count"
      - name: like_count
        description: "tweet's like count"
      - name: quote_count
        description: "number of user profile clicks"
      - name: impression_count
        description: "tweet's impression count"
      - name: user_profile_clicks
        description: "number of clicks in url link"
      - name: url_link_clicks
        description: "time of tweet creation"
      - name: following_count
        description: "user's following count"
      - name: followers_count
        description: "user's followers count at upload day"
      - name: tweet_count
        description: "user's tweets count at upload day"
      - name: listed_count
        description: "user's listed count at upload day"
