version: 2

models:
  - name: mes_brasil
    description: "dbt model for table mes_brasil"
    columns:
      - name: ano
        description: Ano
      - name: mes
        description: Mês
      - name: indice
        description: Número índice (dez 1993 = 100)
      - name: variacao_mensal
        description: Variação percentual mensal
      - name: variacao_trimestral
        description: Variação percentual trimestral
      - name: variacao_semestral
        description: Variação percentual semestral
      - name: variacao_anual
        description: Variação percentual anual
      - name: variacao_doze_meses
        description: Variação percentual doze meses
