version: 2
models :
  - name: test_table
    description: Test table description
    columns:
      - name: ano
        description: ano description
      - name: dado
        description: dado description
      - name: mes
        description: mes description
      - name: sigla_uf
        description: sigla_uf description
