version: 2
models :
  - name: test_table
    description: Test table description
    columns:
      - name: ano
        description: ano description
      - name: dado
        description: dado description
      - name: mes
        description: mes description
      - name: sigla_uf
        description: sigla_uf description
  - name: test_table_laura
    description:
    columns:
      - name: atividade
        description: Atividade do empreendimento
      - name: cedula_mae
        description: Indica se o empreendimento refere-se a uma cédula mãe
      - name: cesta_safra
        description: Cesta de safras do empreendimento
      - name: consorcio
        description: Consórcio do empreendimento
      - name: data_fim
        description: Data de fim do empreendimento
      - name: data_inicio
        description: Data de criação do empreendimento
      - name: finalidade
        description: Finalidade do empreendimento
      - name: id_empreendimento
        description: Código do empreendimento
      - name: id_tipo_cultura
        description: Código do tipo de cultura do empreendimento
      - name: modalidade
        description: Modalidade do empreendimento
      - name: produto
        description: Produto do empreendimento
      - name: unidade_medida
        description: Unidade de medida do produto financiado no empreendimento
      - name: unidade_medida_previsao_producao
        description: Unidade de medida de previsão de produção do produto financiado
          no empreendimento
      - name: variedade
        description: Variedade do empreendimento
      - name: zoneamento
        description: Zoneamento do empreendimento
