version: 2
models :
  - name: densidade_brasil
    description: Densidade de acessos por domicílios de Telefonia móvel no Brasil
      por mês e ano
    columns:
      - name: ano
        description: Ano
      - name: densidade
        description: Densidade de acessos por 100 domicílios
      - name: mes
        description: Mês
  - name: densidade_municipio
    description: Densidade de acessos por domicílios de Telefonia móvel nos municípios
      por mês e ano
    columns:
      - name: ano
        description: Ano
      - name: densidade
        description: Densidade de acessos por 100 domicílios
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: mes
        description: Mês
      - name: sigla_uf
        description: Sigla da Unidade da Federação
  - name: densidade_uf
    description: Densidade de acessos por domicílios de Telefonia móvel nos estados
      por mês e ano
    columns:
      - name: ano
        description: Ano
      - name: densidade
        description: Densidade de acessos por 100 domicílios
      - name: mes
        description: Mês
      - name: sigla_uf
        description: Sigla da Unidade da Federação
  - name: microdados
    description: Dados de telefonia móvel (também conhecido como Serviço Móvel Pessoal)
      a partir de 2019, após reformulação da coleta e divulgação de dados por parte
      da Anatel, que apresentam o município como menor nível de desagregação dos dados.
    columns:
      - name: acessos
        description: Total de contratos sob tais especificações
      - name: ano
        description: Ano
      - name: cnpj
        description: Cadastro Nacional de Pessoa Jurídica
      - name: ddd
        description: Código de Discagem Direta a Distância
      - name: empresa
        description: Nome da companhia ofertante do serviço
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: mes
        description: Mês
      - name: modalidade
        description: Modalidade de contrato, se pré ou pós-pago
      - name: pessoa
        description: Contrato atrelado a Pessoa Física ou Pessoa Jurídica
      - name: porte_empresa
        description: Qualificação do tamanho da companhia
      - name: produto
        description: Tipo de Serviço
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: sinal
        description: Geração de Sistemas Celulares
      - name: tecnologia
        description: Padrão de tecnologia e conectividade dos celulares
