name: Test DBT model

on:
  pull_request:
    types: [labeled, opened]
    branches:
      - master
    paths:
      - 'models/**'
      - '.github/workflows/test_dbt_model.yaml'

jobs:
  test_dbt_model:
    if: contains(github.event.pull_request.labels.*.name, 'test-dev-model')
    name: Test DBT dev model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Get all changed files using a comma separator
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          separator: ','

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-actions.txt

      - name: Run script for syncing DBT schema
        run: |
          python .github/workflows/scripts/table_test.py --modified-files ${{ steps.changed-files.outputs.all_modified_files }} --graphql-url ${{ secrets.BACKEND_GRAPHQL_URL }}

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update metadata'
